import javax.swing.*;
import javax.swing.table.*;
import javax.swing.event.*;

class BazaTowarowDlg extends ResizableDialogBase {
    
    /** Creates new form BazaTowarowDlg */
    public BazaTowarowDlg(java.awt.Frame parent, boolean modal, ITowarHolder Ith) {
        super(parent, "Towary", modal);
        initComponents();
        _Ith = Ith;
        jTable1.setModel(new TowaryModel());
        DefaultListSelectionModel dlsm = new DefaultListSelectionModel();
        dlsm.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        dlsm.addListSelectionListener(new ListSelListener(jButton1, jButton2, jTable1));
        jTable1.setSelectionModel(dlsm);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        _towarSearchDlg = new TowarSearchDialog(parent, true, jTable1);
        restoreDialogPosition();
    }
    
    public void towarAdded()
    {
        int row = DBManager.getInstance().getTowary().size();
        AbstractTableModel m = (AbstractTableModel)jTable1.getModel();
        m.fireTableChanged(new TableModelEvent(jTable1.getModel(), row, row, TableModelEvent.ALL_COLUMNS, TableModelEvent.INSERT));
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;
        
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbSzukaj = new javax.swing.JButton();
        
        getContentPane().setLayout(new java.awt.GridBagLayout());
        
        setTitle("Towary");
        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter()
                          {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });
        
        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 400));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                                                 new Object [][]
                                                                 {
                                                                     
                                                                 },
                                                                 new String []
                                                                 {
                                                                     
                                                                 }
                                                                 ));
        jScrollPane1.setViewportView(jTable1);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 100.0;
        gridBagConstraints.weighty = 100.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);
        
        jButton1.setText("Pobierz z bazy");
        jButton1.addActionListener(new java.awt.event.ActionListener()
                                   {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);
        
        jButton2.setText("Kasuj towar");
        jButton2.addActionListener(new java.awt.event.ActionListener()
                                   {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jButton2, gridBagConstraints);
        
        jbSzukaj.setText("Szukaj...");
        jbSzukaj.addActionListener(new java.awt.event.ActionListener()
                                   {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbSzukajActionPerformed(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jbSzukaj, gridBagConstraints);
        
    }//GEN-END:initComponents
    
    private void jbSzukajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbSzukajActionPerformed
    {//GEN-HEADEREND:event_jbSzukajActionPerformed
        _towarSearchDlg.setVisible(true);
    }//GEN-LAST:event_jbSzukajActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int sel = jTable1.getSelectedRow();
        if (sel == -1)	return;
        String[] options = { "OK", "Anuluj" };
        int res = JOptionPane.showOptionDialog(null, "Czy na pewno chcesz skasowa\u0107 wybrany towar / us\u0142ug\u0119?", "Kasowanie towaru",
                                               JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if (res != 0)
        {
            return;
        }
        TowaryModel twm = (TowaryModel)jTable1.getModel();
        twm.removeRow(sel);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int sel = jTable1.getSelectedRow();
        if (sel == -1)	return;
        TowaryModel twm = (TowaryModel)jTable1.getModel();
        _Ith.setNazwa((String)twm.getValueAt(sel, 0));
        _Ith.setCena((String)twm.getValueAt(sel, 1));
        _Ith.setJednostka((String)twm.getValueAt(sel, 2));
        _Ith.setSWW((String)twm.getValueAt(sel, 3));
        _Ith.setVAT((String)twm.getValueAt(sel, 4));
        
        saveDialogPosition();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        saveDialogPosition();
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbSzukaj;
    // End of variables declaration//GEN-END:variables
    private ITowarHolder _Ith;
    private TowarSearchDialog _towarSearchDlg;
}
