import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import java.awt.Point;
import java.awt.Rectangle;

class KlientSearchDialog extends ResizableDialogBase
{
    public KlientSearchDialog(java.awt.Frame parent, boolean modal, JTable table)
    {
        super(parent, "Szukanie klienta", modal, new java.awt.Rectangle(0, 0, 300, 200));
        _Table = table;
        initComponents();
        _Adres.addActionListener(new editAL());
        _Nip.addActionListener(new editAL());
        _Nazwa.addActionListener(new editAL());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jbOK = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        _Nip = new javax.swing.JTextField();
        _Nazwa = new javax.swing.JTextField();
        _Adres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Szukanie klienta");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbOKActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jbOK, gridBagConstraints);

        jbCancel.setText("Zamknij");
        jbCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCancelActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jbCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_Nip, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_Nazwa, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_Adres, gridBagConstraints);

        jLabel1.setText("NIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Nazwa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Ulica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(jLabel3, gridBagConstraints);

    }//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCancelActionPerformed
    {//GEN-HEADEREND:event_jbCancelActionPerformed
        saveDialogPosition();
        closeDialog(null);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbOKActionPerformed
    {//GEN-HEADEREND:event_jbOKActionPerformed
       szukaj();
    }//GEN-LAST:event_jbOKActionPerformed
    private void szukaj()
    {
       int pos = searchForIdx(_Nip.getText(), _Nazwa.getText(), _Adres.getText(), _Table.getSelectedRow());
        if (pos != -1)
        {
            _Table.setRowSelectionInterval(pos, pos);
            JViewport viewport = (JViewport)_Table.getParent();
            Rectangle rect = _Table.getCellRect(pos, 0, true);
            Point pt = viewport.getViewPosition();
            rect.setLocation(rect.x - pt.x, rect.y - pt.y);
            viewport.scrollRectToVisible(rect);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nie znaleziono klienta spe³niaj¹cego warunki wyszukiwania", "Nie znaleziono", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    private int searchForIdx(String Nip, String Nazwa, String Adres, int fromPos)
    {
        ++fromPos;
        Nip.trim();
        Nazwa.trim();
        Adres.trim();
        ArrayList klienciL = DBManager.getInstance().getKlienci();
        int cnt = klienciL.size();
        Klient k;
        for (int i = 0; i < cnt; ++i)
        {
            k = (Klient)klienciL.get((fromPos + i) % cnt);
            if (!(Nip.length() == 0) && (k.getNIP().toUpperCase().indexOf(Nip.toUpperCase()) == -1)) continue;
            if (!(Adres.length() == 0) && (k.getUlica().toUpperCase().indexOf(Adres.toUpperCase()) == -1)) continue;
            if (!(Nazwa.length() == 0) && (k.getNazwa().toUpperCase().indexOf(Nazwa.toUpperCase()) == -1)) continue;
            return (i + fromPos) % cnt;
        }
        return -1;
    }
        
    private class editAL implements java.awt.event.ActionListener
    {
        public void actionPerformed(java.awt.event.ActionEvent e)
        {
            szukaj();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _Adres;
    private javax.swing.JTextField _Nazwa;
    private javax.swing.JTextField _Nip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    // End of variables declaration//GEN-END:variables
    private JTable _Table;
}
