import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.JOptionPane;
import javax.swing.JViewport;
import java.awt.Point;
import java.awt.Rectangle;

class TowarSearchDialog extends ResizableDialogBase
{
   public TowarSearchDialog(java.awt.Frame parent, boolean modal, JTable table)
   {
        super(parent, "Szukanie towaru", modal, new java.awt.Rectangle(0, 0, 300, 200));
        _Table = table;
        initComponents();
        _SWW.addActionListener(new editAL());
        _Cena.addActionListener(new editAL());
        _Nazwa.addActionListener(new editAL());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;

        _Nazwa = new javax.swing.JTextField();
        _Cena = new javax.swing.JTextField();
        _SWW = new javax.swing.JTextField();
        jbSzukaj = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_Nazwa, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_Cena, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(_SWW, gridBagConstraints);

        jbSzukaj.setText("Szukaj");
        jbSzukaj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbSzukajActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jbSzukaj, gridBagConstraints);

        jbCancel.setText("Zamknij");
        jbCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbCancelActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jbCancel, gridBagConstraints);

        jLabel1.setText("Nazwa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("PKWiU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Cena");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 10.0;
        getContentPane().add(jLabel3, gridBagConstraints);

    }//GEN-END:initComponents

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbCancelActionPerformed
    {//GEN-HEADEREND:event_jbCancelActionPerformed
        saveDialogPosition();
        closeDialog(null);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jbSzukajActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbSzukajActionPerformed
    {//GEN-HEADEREND:event_jbSzukajActionPerformed
        szukaj();
    }//GEN-LAST:event_jbSzukajActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    
    private int searchForIdx(String Nazwa, String SWW, String Cena, int fromPos)
    {
        ++fromPos;
        Cena.trim();
        Nazwa.trim();
        SWW.trim();
        ArrayList towaryL = DBManager.getInstance().getTowary();
        int cnt = towaryL.size();
        Towar t;
        for (int i = 0; i < cnt; ++i)
        {
            t = (Towar)towaryL.get((fromPos + i) % cnt);
            if (!(Cena.length() == 0) && (t.getCena().toUpperCase().indexOf(Cena.toUpperCase()) == -1)) continue;
            if (!(SWW.length() == 0) && (t.getSWW().toUpperCase().indexOf(SWW.toUpperCase()) == -1)) continue;
            if (!(Nazwa.length() == 0) && (t.getNazwa().toUpperCase().indexOf(Nazwa.toUpperCase()) == -1)) continue;
            return (i + fromPos) % cnt;
        }
        return -1;
    }
    
    private void szukaj()
    {
       int pos = searchForIdx(_Nazwa.getText(), _SWW.getText(), _Cena.getText(), _Table.getSelectedRow());
        if (pos != -1)
        {
            _Table.setRowSelectionInterval(pos, pos);
            JViewport viewport = (JViewport)_Table.getParent();
            Rectangle rect = _Table.getCellRect(pos, 0, true);
            Point pt = viewport.getViewPosition();
            rect.setLocation(rect.x - pt.x, rect.y - pt.y);
            viewport.scrollRectToVisible(rect);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Nie znaleziono towaru / us\u0142ugi spe\u0142niaj\u0105cej warunki wyszukiwania", "Nie znaleziono", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private class editAL implements java.awt.event.ActionListener
    {
        public void actionPerformed(java.awt.event.ActionEvent e)
        {
            szukaj();
        }
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField _Cena;
    private javax.swing.JTextField _Nazwa;
    private javax.swing.JTextField _SWW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbSzukaj;
    // End of variables declaration//GEN-END:variables
    private JTable _Table;
}
